DECLARE
    DIR DIRECCION := NEW DIRECCION ('AV LA LIBERTAD', 'LEON', 24193);
    DIR2 DIRECCION := NEW DIRECCION ('AV PROFESOR GARCIA', 'MADRID', 45002);
    PERSONA1 PERSONA := NEW PERSONA (1, 'JUAN', DIR, SYSDATE);
    PERSONA2 PERSONA := NEW PERSONA (2, 'LUCÍA', DIR2, SYSDATE);
    ALUMNO1 T_ALUMNO := NEW T_ALUMNO (PERSONA1, 1, 6, 3);
    ALUMNO2 T_ALUMNO := NEW T_ALUMNO (PERSONA2, 8, 5, 7);
BEGIN
    DBMS_OUTPUT.PUT_LINE('NOMBRE: '|| ALUMNO1.PERSON.NOMBRE ||' NOTA 1: ' || ALUMNO1.NOTA1 ||' NOTA 2: ' || ALUMNO1.NOTA2||' NOTA 3: ' || ALUMNO1.NOTA3);
    DBMS_OUTPUT.PUT_LINE('NOMBRE: '|| ALUMNO2.PERSON.NOMBRE ||' NOTA 1: ' || ALUMNO2.NOTA1 ||' NOTA 2: ' || ALUMNO2.NOTA2||' NOTA 3: ' || ALUMNO2.NOTA3);
END;