package primero;
// Generated 27-ene-2021 8:50:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Vuelo generated by hbm2java
 */
public class Vuelo implements java.io.Serializable {

	private int numVuelo;
	private Sucursal sucursal;
	private Date fecha;
	private Date hora;
	private String origen;
	private String destino;
	private int plazasTotales;
	private int plazasTuristas;

	public Vuelo() {
	}

	public Vuelo(int numVuelo, Sucursal sucursal, Date fecha, Date hora, String origen, String destino,
			int plazasTotales, int plazasTuristas) {
		this.numVuelo = numVuelo;
		this.sucursal = sucursal;
		this.fecha = fecha;
		this.hora = hora;
		this.origen = origen;
		this.destino = destino;
		this.plazasTotales = plazasTotales;
		this.plazasTuristas = plazasTuristas;
	}

	public int getNumVuelo() {
		return this.numVuelo;
	}

	public void setNumVuelo(int numVuelo) {
		this.numVuelo = numVuelo;
	}

	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	public int getPlazasTotales() {
		return this.plazasTotales;
	}

	public void setPlazasTotales(int plazasTotales) {
		this.plazasTotales = plazasTotales;
	}

	public int getPlazasTuristas() {
		return this.plazasTuristas;
	}

	public void setPlazasTuristas(int plazasTuristas) {
		this.plazasTuristas = plazasTuristas;
	}

}
